---
services:
  db:
    image: https://hub.docker.com/repository/docker/chandrikadevops/repooo:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 3


   auth_service:
    image: https://hub.docker.com/repository/docker/chandrikadevops/repooo:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 3

   book_service:
    image: https://hub.docker.com/repository/docker/chandrikadevops/repooo:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 3


   borrow_service:
    image: https://hub.docker.com/repository/docker/chandrikadevops/repooo:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 3

   frontend_service:
     image: https://hub.docker.com/repository/docker/chandrikadevops/repooo:frontendimage
     ports:
       - "5000:5000"
     deploy:
       replicas: 3
